name: CD
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  release-helm-chart:
    name: Release Helm chart
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - run: |
        git config user.name "$GITHUB_ACTOR"
        git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
    - uses: helm/chart-releaser-action@v1.7.0
      with:
        config: "./.github/configs/cr.yaml"
      env:
        CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
